import typescript from '@rollup/plugin-typescript';

export default {
  input: 'src/index.ts', // Replace with your entry point
  output: {
    file: 'build/bundle.js',
    format: 'iife', // Choose the desired output format,
    sourcemap: true
  },
  plugins: [
    typescript({
      sourceMap: true // Ensure sourcemaps are generated by the plugin
    })
  ]
};
